require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe LiveProgramsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # LiveProgram. As you add validations to LiveProgram, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LiveProgramsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all live_programs as @live_programs" do
      live_program = LiveProgram.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:live_programs)).to eq([live_program])
    end
  end

  describe "GET #show" do
    it "assigns the requested live_program as @live_program" do
      live_program = LiveProgram.create! valid_attributes
      get :show, {:id => live_program.to_param}, valid_session
      expect(assigns(:live_program)).to eq(live_program)
    end
  end

  describe "GET #new" do
    it "assigns a new live_program as @live_program" do
      get :new, {}, valid_session
      expect(assigns(:live_program)).to be_a_new(LiveProgram)
    end
  end

  describe "GET #edit" do
    it "assigns the requested live_program as @live_program" do
      live_program = LiveProgram.create! valid_attributes
      get :edit, {:id => live_program.to_param}, valid_session
      expect(assigns(:live_program)).to eq(live_program)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new LiveProgram" do
        expect {
          post :create, {:live_program => valid_attributes}, valid_session
        }.to change(LiveProgram, :count).by(1)
      end

      it "assigns a newly created live_program as @live_program" do
        post :create, {:live_program => valid_attributes}, valid_session
        expect(assigns(:live_program)).to be_a(LiveProgram)
        expect(assigns(:live_program)).to be_persisted
      end

      it "redirects to the created live_program" do
        post :create, {:live_program => valid_attributes}, valid_session
        expect(response).to redirect_to(LiveProgram.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved live_program as @live_program" do
        post :create, {:live_program => invalid_attributes}, valid_session
        expect(assigns(:live_program)).to be_a_new(LiveProgram)
      end

      it "re-renders the 'new' template" do
        post :create, {:live_program => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested live_program" do
        live_program = LiveProgram.create! valid_attributes
        put :update, {:id => live_program.to_param, :live_program => new_attributes}, valid_session
        live_program.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested live_program as @live_program" do
        live_program = LiveProgram.create! valid_attributes
        put :update, {:id => live_program.to_param, :live_program => valid_attributes}, valid_session
        expect(assigns(:live_program)).to eq(live_program)
      end

      it "redirects to the live_program" do
        live_program = LiveProgram.create! valid_attributes
        put :update, {:id => live_program.to_param, :live_program => valid_attributes}, valid_session
        expect(response).to redirect_to(live_program)
      end
    end

    context "with invalid params" do
      it "assigns the live_program as @live_program" do
        live_program = LiveProgram.create! valid_attributes
        put :update, {:id => live_program.to_param, :live_program => invalid_attributes}, valid_session
        expect(assigns(:live_program)).to eq(live_program)
      end

      it "re-renders the 'edit' template" do
        live_program = LiveProgram.create! valid_attributes
        put :update, {:id => live_program.to_param, :live_program => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested live_program" do
      live_program = LiveProgram.create! valid_attributes
      expect {
        delete :destroy, {:id => live_program.to_param}, valid_session
      }.to change(LiveProgram, :count).by(-1)
    end

    it "redirects to the live_programs list" do
      live_program = LiveProgram.create! valid_attributes
      delete :destroy, {:id => live_program.to_param}, valid_session
      expect(response).to redirect_to(live_programs_url)
    end
  end

end
